before_script:
  - docker info
  - git status

build:
  stage: build
  script:
    - docker build -t prodex/web:test .

.login_and_build:
  before_script:
    - $(aws ecr get-login --no-include-email --region us-east-1 --profile echo)
    - docker build -t prodex/web:test .

deploy_dev:
  extends: .login_and_build
  stage: deploy
  resource_group: dev
  script:
    - docker tag prodex/web:test 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:dev
    - docker push 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web
    - docker rmi 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:dev
  only:
    - /^\d\.\d\..*/

deploy_review:
  extends: .login_and_build
  stage: deploy
  resource_group: review
  script:
    - docker tag prodex/web:test 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:review
    - docker push 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web
    - docker rmi 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:review
  when: manual
  only:
    - /^\d\.\d\..*/

deploy_staging:
  extends: .login_and_build
  stage: deploy
  resource_group: staging
  script:
    - docker tag prodex/web:test 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:stage
    - docker push 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web
    - docker rmi 097989233947.dkr.ecr.us-east-1.amazonaws.com/prodex/web:stage
  when: manual
  only:
    - /^\d\.\d\..*/

cleanup:
  stage: .post
  when: always
  script:
  - docker rmi $(docker images -q prodex/web:test) || exit 0
  - docker system prune --volumes -f || exit 0